### ISSUE TITLE
[shared-ini-file-loader] CredentialsProviderError using SSO session profiles caused by regression since 2.1.0

### ISSUE THREAD

**Issue by stevensdavid** [awslabs/smithy-typescript#1026] opened 2023-10-12 09:29 UTC
There seems to have been a regression in 2.2.0 of `@smithy/shared-ini-file-loader` that breaks my SSO sesssion profile setup. Consider the following program:
```js
import { GetCallerIdentityCommand, STS } from "@aws-sdk/client-sts";

const run = async () => {
  const client = new STS({ region: "eu-west-1" });
  console.log(await client.send(new GetCallerIdentityCommand({})));
};

run();
```
If this is run with the following `package.json`:
```json
{
  "dependencies": {
    "@aws-sdk/client-sts": "3.427.0"
  }
}
```
using 
```bash
rm package-lock.json; rm -rf node_modules && npm i && AWS_PROFILE=<SSO_SESSION_PROFILE_NAME> ts-node index.ts
```
then I receive the output
```
CredentialsProviderError: Could not load credentials from any providers
    at test/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at test/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (test/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async SignatureV4.credentialProvider (test/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.signRequest (test/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:106:29)
    at async test/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:16:18
    at async test/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async run (test/index.ts:5:15) {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```
If I instead override the package version using
```json
{
  "dependencies": {
    "@aws-sdk/client-sts": "3.427.0"
  },
  "overrides": {
    "@aws-sdk/client-sts": {
      "@smithy/shared-ini-file-loader": "2.1.0"
    }
  }
}
```
then the code functions as it should.

The `~/.aws/config` file has the following structure:
```ini
[sso-session <ROOT_SESSION>]
sso_start_url=https://<ID>.awsapps.com/start
sso_region=eu-west-1
sso_registration_scopes=sso:account:access

[profile <SSO_SESSION_PROFILE_NAME>]
sso_account_id=<ACCOUNT>
sso_role_name=<SSO_ROLE_NAME>
sso_session=<ROOT_SESSION>
region=eu-west-1
```

**Comment by trivikr** [comment] 2023-10-12 16:22
We'd changed the way ini file contents were parsed in https://github.com/awslabs/smithy-typescript/pull/993, which was released in `v2.2.0`
However, our unit tests verify that it's not affected the way we get `getSsoSessionData`

Unit tests for parsing sections: https://github.com/awslabs/smithy-typescript/blob/3a5afa42519acb9a8be6542c799129b769a17fb7/packages/shared-ini-file-loader/src/parseIni.spec.ts#L49-L59
* mock input: `[sso-session mock_section_name]\nkey=value\n`
* parsed output: `{ 'sso-session.mock_section_name': { key: 'value' } }`

Unit tests for loading https://github.com/awslabs/smithy-typescript/blob/3a5afa42519acb9a8be6542c799129b769a17fb7/packages/shared-ini-file-loader/src/getSsoSessionData.spec.ts#L36-L40
* mock input:
```console
{
    'sso-session.one': {
      key_one_1: 'value_one_1',
      key_one_2: 'value_one_2',
      key_one_3: 'value_one_3'
    }
}
```
* mock output:
```console
{
    one: {
      key_one_1: 'value_one_1',
      key_one_2: 'value_one_2',
      key_one_3: 'value_one_3'
    }
}
```

I'll check if anything else needs to be updated.

**Comment by trivikr** [comment] 2023-10-12 16:42
I checked if direct usage of `parseKnownFiles` in AWS SDK packages can cause regression.
It shouldn't, since we started populating subsections in `@smithy/shared-ini-file-loader@2.2.0` which weren't populated before.

Example call in `@aws-sdk/credential-provider-sso`
https://github.com/aws/aws-sdk-js-v3/blob/39126a49b1750fabd059a3cb2abd3b89917d6b02/packages/credential-provider-sso/src/fromSSO.ts#L87

Example config file:
```console
$ cat ~/.aws/config
[sso-session sso-session-name]
sso_start_url=https://<ID>.awsapps.com/start
sso_region=eu-west-1
sso_registration_scopes=sso:account:access

[profile sso-session-profile]
sso_account_id=<ACCOUNT>
sso_role_name=<SSO_ROLE_NAME>
sso_session=sso-session-name
region=eu-west-1
```

Test code:
```js
import { parseKnownFiles } from "@smithy/shared-ini-file-loader";

console.log(await parseKnownFiles());
```

With `@smithy/shared-ini-file-loader@2.2.0`
```console
{
  'sso-session.sso-session-name': {
    sso_start_url: 'https://<ID>.awsapps.com/start',
    sso_region: 'eu-west-1',
    sso_registration_scopes: 'sso:account:access'
  },
  'sso-session-profile': {
    sso_account_id: '<ACCOUNT>',
    sso_role_name: '<SSO_ROLE_NAME>',
    sso_session: 'sso-session-name',
    region: 'eu-west-1'
  }
}
```

With `@smithy/shared-ini-file-loader@2.1.0`
```console
{
  'sso-session-profile': {
    sso_account_id: '<ACCOUNT>',
    sso_role_name: '<SSO_ROLE_NAME>',
    sso_session: 'sso-session-name',
    region: 'eu-west-1'
  }
}
```

**Comment by trivikr** [comment] 2023-10-12 17:44
I'm not able to reproduce the issue using `fromSSO` in my setup

AWS Configuration
```console
[profile sso-session-profile]
sso_session = sso-session-name
sso_account_id = <ACCOUNT>
sso_role_name =<SSO_ROLE_NAME>
region = us-east-1

[sso-session sso-session-name]
sso_start_url = https://<ID>.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

Test code:
```js
import { fromSSO } from "@aws-sdk/credential-provider-sso";

console.log(await fromSSO({ profile: "sso-session-profile" })());
```

Testing with `@aws-sdk/credential-provider-sso@3.427.0`
```console
$ npm --version
9.8.1

$ npm list @aws-sdk/credential-provider-sso
test@1.0.0 /Users/trivikr/workspace/test
└── @aws-sdk/credential-provider-sso@3.427.0

$ npm list @smithy/shared-ini-file-loader
test@1.0.0 /Users/trivikr/workspace/test
└─┬ @aws-sdk/credential-provider-sso@3.427.0
  ├─┬ @aws-sdk/client-sso@3.427.0
  │ ├─┬ @smithy/middleware-endpoint@2.1.1
  │ │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  │ └─┬ @smithy/node-config-provider@2.1.1
  │   └── @smithy/shared-ini-file-loader@2.2.0 deduped
  ├─┬ @aws-sdk/token-providers@3.427.0
  │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  └── @smithy/shared-ini-file-loader@2.2.0

$ node test.mjs
{
  accessKeyId: '<REDACTED>',
  secretAccessKey: '<REDACTED>',
  sessionToken: '<REDACTED>',
  expiration: 2023-10-12T18:38:37.000Z
}
```

**Comment by trivikr** [comment] 2023-10-12 17:50
I'm not able to reproduce with `@aws-sdk/client-sts` too.

Test code:
```js
import { STS } from "@aws-sdk/client-sts";

const client = new STS({
  region: "us-east-1",
  profile: "sso-session-profile",
});
console.log(await client.getCallerIdentity());
```

Execution:
```
$ npm list @aws-sdk/client-sts
test@1.0.0 /Users/trivikr/workspace/test
└── @aws-sdk/client-sts@3.427.0

$ npm list @smithy/shared-ini-file-loader
test@1.0.0 /Users/trivikr/workspace/test
└─┬ @aws-sdk/client-sts@3.427.0
  ├─┬ @aws-sdk/credential-provider-node@3.427.0
  │ ├─┬ @aws-sdk/credential-provider-ini@3.427.0
  │ │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  │ ├─┬ @aws-sdk/credential-provider-process@3.425.0
  │ │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  │ ├─┬ @aws-sdk/credential-provider-sso@3.427.0
  │ │ ├─┬ @aws-sdk/token-providers@3.427.0
  │ │ │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  │ │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  │ └── @smithy/shared-ini-file-loader@2.2.0
  ├─┬ @smithy/middleware-endpoint@2.1.1
  │ └── @smithy/shared-ini-file-loader@2.2.0 deduped
  └─┬ @smithy/node-config-provider@2.1.1
    └── @smithy/shared-ini-file-loader@2.2.0 deduped

$ node test.mjs
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '1a1ecb8d-4d31-4dad-95ed-eb496b301f45',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  UserId: '<REDACTED>',
  Account: '<REDACTED>',
  Arn: '<REDACTED>'
}
```

**Comment by trivikr** [comment] 2023-10-12 17:53
@stevensdavid Is there any additional information you can provide with your setup to help us debug the issue further?

For example, the profile name used, or the package manager used, or the node version used?
The test code you provided does not pass `profile` during client creation. That could also be an issue.

**Comment by stevensdavid** [comment] 2023-10-13 12:38
Hi! Thank you for looking in to this. I did some more testing and it seems like the thing that causes the error is having a `@`-symbol in the profile name (my profiles have names like `admin@prod`) - this works in the CLI, AWS SDK v2 and when using the earlier mentioned override. When I make a copy of the profile which removes the @-symbol, it works again.

I'm running Node `20.5.1` and npm `9.8.0`, and got rid of ts-node to get rid of another variable 😅 

The same behaviour is also happening with

```js
const { fromSSO } = require("@aws-sdk/credential-provider-sso");

fromSSO({ profile: "admin@prod" })().then(console.log);
```
throwing 
```
CredentialsProviderError: Profile admin@prod was not found.
    at test/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js:16:19 {
  tryNextLink: true
}
```
while 
```js
const { fromSSO } = require("@aws-sdk/credential-provider-sso");

fromSSO({ profile: "admin@prod" })().then(console.log);
```
works. Did something change regarding which characters are considered valid profile names during parsing?

**Comment by trivikr** [comment] 2023-10-13 15:32
> I did some more testing and it seems like the thing that causes the error is having a `@`-symbol in the profile name (my profiles have names like `admin@prod`)

The ampersand key is not allowed in profile names, as per [SDK Reference](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#section-types)
> You can use letters, numbers, hyphens ( `-` ), and underscores ( `_` ), but no spaces.

It's possible that `@` key was parsed earlier by shared-ini-parser.
I'll investigate if we can parse unsupported `@` key in profile names.

**Comment by trivikr** [comment] 2023-10-13 15:43
The repro for invalid profile name with `@` in it:

Config:
```console
$ cat ~/.aws/config 
[sso-session sso-session-name]
sso_start_url=https://<ID>.awsapps.com/start
sso_region=eu-west-1
sso_registration_scopes=sso:account:access

[profile admin@prod]
sso_account_id=<ACCOUNT>
sso_role_name=<SSO_ROLE_NAME>
sso_session=sso-session-name
region=eu-west-1
```

Code:
```js
import { parseKnownFiles } from "@smithy/shared-ini-file-loader";

console.log(await parseKnownFiles());
```

Output with `v2.1.0`
```json
{
  'admin@prod': {
    sso_account_id: '<ACCOUNT>',
    sso_role_name: '<SSO_ROLE_NAME>',
    sso_session: 'sso-session-name',
    region: 'eu-west-1'
  }
}
```

Output with `v2.2.0`
```json
{
  'sso-session.sso-session-name': {
    sso_start_url: 'https://<ID>.awsapps.com/start',
    sso_region: 'eu-west-1',
    sso_registration_scopes: 'sso:account:access'
  }
}
```

This happens as we do not parse invalid `@` character in our regular expression in https://github.com/awslabs/smithy-typescript/blob/5bd468207b89582224762a6c0f7001d51766c1bd/packages/shared-ini-file-loader/src/parseIni.ts#L5

It used to get incorrectly parsed earlier.

**Closed** 2023-10-13 16:46 UTC
